export default {
  CHECK_IN_GUEST_PENDING: 'CHECK_IN_GUEST_PENDING',
  CHECK_IN_GUEST_SUCCESS: 'CHECK_IN_GUEST_SUCCESS',
  CHECK_IN_GUEST_FAILURE: 'CHECK_IN_GUEST_FAILURE',

  CHECK_OUT_GUEST_PENDING: 'CHECK_OUT_GUEST_PENDING',
  CHECK_OUT_GUEST_SUCCESS: 'CHECK_OUT_GUEST_SUCCESS',
  CHECK_OUT_GUEST_FAILURE: 'CHECK_OUT_GUEST_FAILURE',

  GET_GUESTS_PENDING: 'GET_GUESTS_PENDING',
  GET_GUESTS_SUCCESS: 'GET_GUESTS_SUCCESS',
  GET_GUESTS_FAILURE: 'GET_GUESTS_FAILURE',
};
