version: '3.1'
services:
  mongo:
    image: mongo:3.6.1
    ports:
      - "${DB_PORT}:27017"
    restart: always
    env_file: .env
    command: --smallfiles
    container_name: home_sweet_home_db
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"